steps:
  # Get latest version
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args: ["get-version", "${_REPO_OWNER}", "github-ops-cli"]
    secretEnv: ["GITHUB_TOKEN"]
    id: "get-version"

  # Process PR info and bump version
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Debug environment variables:"
        echo "PR_TYPE value: ${_PR_TYPE}"
        echo "IS_MERGE value: ${_IS_MERGE}"

        VERSION_TYPE="${_PR_TYPE}"
        if [ -z "${_PR_TYPE}" ]; then
          VERSION_TYPE="timestamp"
        fi

        python /usr/local/bin/cli.py \
          --action bump-version \
          --repo-owner ${_REPO_OWNER} \
          --repo-name github-ops-cli \
          --current-version "$$(cat current_version.txt)" \
          --version-type "$${VERSION_TYPE}" \
          --is-merge "${_IS_MERGE}" \
          --pr-number "${_PR_NUMBER}"
    secretEnv: ["GITHUB_TOKEN"]
    id: "bump-version"
    waitFor: ["get-version"]

  # Deploy the docker image
  - name: us-central1-docker.pkg.dev/${PROJECT_ID}/docker/dev-tools-builder-packer
    entrypoint: "make"
    args: ["deploy"]
    env:
      - "BUILDER_TAG=$$(cat new_version.txt)"
    secretEnv: ["GITHUB_TOKEN"]
    id: "deploy"
    waitFor: ["bump-version"]

  # Create GitHub release
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "create-release"
      - "${_REPO_OWNER}"
      - "${_REPO}"
      - "--current-version"
      - "$$(cat new_version.txt)"
      - "--is-prod"
      - "${_IS_MERGE}"
      - "--skip-asset"
    secretEnv: ["GITHUB_TOKEN"]
    waitFor: ["deploy"]
    id: "create-release"

  # Update parent repo submodule
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      [
        "--action",
        "update-submodule",
        "--repo-owner",
        "${_REPO_OWNER}",
        "--repo-name",
        "${_REPO}",
        "--parent-repo",
        "${_PARENT_REPO}",
        "--submodule-path",
        "${_SUBMODULE_PATH}",
        "--current-version",
        "$$(cat new_version.txt)",
        "--is-merge",
        "${_IS_MERGE}",
      ]
    secretEnv: ["GITHUB_TOKEN"]
    id: "update-submodule"
    waitFor: ["create-release"]

substitutions:
  _LOCATION: us-central1
  _REPO_OWNER: ""
  _REPO: "github-ops-cli"
  _PR_TYPE: "" # Populated by the PR label if it exists
  _IS_MERGE: "false"
  _PR_NUMBER: "" # PR number for reference
  _PARENT_REPO: "portfolio" # Parent repository name
  _SUBMODULE_PATH: "assets/scripts/github-ops-cli" # Path to submodule in parent repo

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/$PROJECT_ID/serviceAccounts/cloud-builder@${PROJECT_ID}.iam.gserviceaccount.com"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: "GITHUB_TOKEN"
